package com.eztila.kartdefterim;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.*;import android.text.InputType;import android.view.*;import android.widget.*;import org.json.*;import java.text.*;import java.util.*;

public class MainActivity extends Activity{
 final int BG=Color.rgb(246,247,251),TEXT=Color.rgb(25,31,45),MUTED=Color.rgb(108,117,137),BLUE=Color.rgb(49,87,213),RED=Color.rgb(203,66,66),GREEN=Color.rgb(27,142,86); final Locale TR=new Locale("tr","TR");
 final String[] BANKS={"VakıfBank","Ziraat Bankası","TEB","Türkiye İş Bankası","Garanti BBVA","Akbank","Yapı Kredi","QNB Türkiye","Halkbank","DenizBank","Kuveyt Türk","Albaraka Türk","Enpara","Diğer"};
 SharedPreferences p; JSONArray cards=new JSONArray(); LinearLayout body;
 public void onCreate(Bundle b){super.onCreate(b);p=getSharedPreferences("kart_defterim",0);load();summary();}
 int d(int n){return Math.round(n*getResources().getDisplayMetrics().density);} GradientDrawable bg(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(d(r));return g;}
 TextView t(String s,int z,int c,boolean b){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);if(b)v.setTypeface(null,1);return v;} String money(double x){return NumberFormat.getCurrencyInstance(TR).format(x);} void load(){try{cards=new JSONArray(p.getString("cards","[]"));}catch(Exception e){cards=new JSONArray();}} void save(){p.edit().putString("cards",cards.toString()).apply();}
 Button btn(String s,int c){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(Color.WHITE);b.setBackground(bg(c,12));return b;}
 LinearLayout box(){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setPadding(d(16),d(16),d(16),d(16));x.setBackground(bg(Color.WHITE,18));return x;}
 void screen(String sub,int tab){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);LinearLayout h=new LinearLayout(this);h.setOrientation(LinearLayout.VERTICAL);h.setPadding(d(20),d(16),d(20),d(12));h.addView(t("KART DEFTERİM",20,TEXT,true));h.addView(t(sub,13,MUTED,false));root.addView(h);ScrollView sv=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(d(16),d(8),d(16),d(20));sv.addView(body);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));LinearLayout nav=new LinearLayout(this);String[] n={"Özet","Kartlar","İşlemler"};for(int i=0;i<3;i++){Button b=new Button(this);b.setText(n[i]);b.setAllCaps(false);b.setTextColor(i==tab?BLUE:MUTED);b.setBackgroundColor(Color.WHITE);final int q=i;b.setOnClickListener(v->{if(q==0)summary();else if(q==1)listCards();else transactions();});nav.addView(b,new LinearLayout.LayoutParams(0,d(58),1));}root.addView(nav);setContentView(root);}
 void title(String s){TextView x=t(s,17,TEXT,true);LinearLayout.LayoutParams l=new LinearLayout.LayoutParams(-1,-2);l.setMargins(0,d(18),0,d(9));body.addView(x,l);} LinearLayout metric(String a,String b){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.addView(t(a,12,MUTED,false));x.addView(t(b,17,TEXT,true));return x;}
 double debt(JSONObject c){double x=c.optDouble("debt",0);JSONArray a=c.optJSONArray("tx");if(a!=null)for(int i=0;i<a.length();i++){JSONObject z=a.optJSONObject(i);if(z!=null)x+=(z.optString("type").equals("expense")?1:-1)*z.optDouble("amount");}return Math.max(0,x);}
 void summary(){screen("Genel durum",0);double lim=0,de=0,ex=0,in=0;Calendar now=Calendar.getInstance();for(int i=0;i<cards.length();i++){JSONObject c=cards.optJSONObject(i);if(c==null)continue;lim+=c.optDouble("limit");de+=debt(c);JSONArray a=c.optJSONArray("tx");if(a!=null)for(int j=0;j<a.length();j++){JSONObject z=a.optJSONObject(j);if(z!=null&&month(z.optLong("date"),now)){if(z.optString("type").equals("expense"))ex+=z.optDouble("amount");else in+=z.optDouble("amount");}}}LinearLayout s=box();s.addView(t("Toplam güncel borç",13,MUTED,false));s.addView(t(money(de),30,TEXT,true));LinearLayout r=new LinearLayout(this);r.addView(metric("Toplam limit",money(lim)),new LinearLayout.LayoutParams(0,-2,1));r.addView(metric("Kullanılabilir",money(Math.max(0,lim-de))),new LinearLayout.LayoutParams(0,-2,1));s.addView(r);LinearLayout m=new LinearLayout(this);m.setPadding(0,d(14),0,0);m.addView(metric("Bu ay harcama",money(ex)),new LinearLayout.LayoutParams(0,-2,1));m.addView(metric("Ödeme / iade",money(in)),new LinearLayout.LayoutParams(0,-2,1));s.addView(m);body.addView(s);title("Kartlar");Button add=btn("+ Kart ekle",BLUE);add.setOnClickListener(v->addCard());body.addView(add,new LinearLayout.LayoutParams(-1,d(48)));if(cards.length()==0)note("Henüz kart eklenmedi. İlk kartınızı ekleyerek harcamaları takip etmeye başlayın.");else for(int i=0;i<Math.min(3,cards.length());i++)cardRow(i);title("Son işlemler");if(!recent(5))note("Henüz işlem yok.");}
 boolean month(long ms,Calendar n){Calendar c=Calendar.getInstance();c.setTimeInMillis(ms);return c.get(1)==n.get(1)&&c.get(2)==n.get(2);} void note(String s){LinearLayout b=box();b.addView(t(s,13,MUTED,false));LinearLayout.LayoutParams l=new LinearLayout.LayoutParams(-1,-2);l.setMargins(0,d(9),0,0);body.addView(b,l);}
 void listCards(){screen("Kartlarım",1);Button add=btn("+ Yeni kart ekle",BLUE);add.setOnClickListener(v->addCard());body.addView(add,new LinearLayout.LayoutParams(-1,d(48)));if(cards.length()==0)note("Henüz kart eklenmedi.");for(int i=0;i<cards.length();i++)cardRow(i);}
 void cardRow(int i){JSONObject c=cards.optJSONObject(i);if(c==null)return;LinearLayout b=box();b.setClickable(true);b.setOnClickListener(v->detail(i));b.addView(t(c.optString("bank"),16,TEXT,true));b.addView(t(c.optString("name"),12,MUTED,false));LinearLayout r=new LinearLayout(this);r.setPadding(0,d(12),0,0);r.addView(metric("Borç",money(debt(c))),new LinearLayout.LayoutParams(0,-2,1));r.addView(metric("Kullanılabilir",money(Math.max(0,c.optDouble("limit")-debt(c)))),new LinearLayout.LayoutParams(0,-2,1));b.addView(r);LinearLayout.LayoutParams l=new LinearLayout.LayoutParams(-1,-2);l.setMargins(0,d(10),0,0);body.addView(b,l);}
 void detail(int idx){JSONObject c=cards.optJSONObject(idx);if(c==null)return;screen(c.optString("bank")+" • "+c.optString("name"),1);LinearLayout b=box();b.addView(t("Güncel borç",12,MUTED,false));b.addView(t(money(debt(c)),30,TEXT,true));LinearLayout r=new LinearLayout(this);r.addView(metric("Limit",money(c.optDouble("limit"))),new LinearLayout.LayoutParams(0,-2,1));r.addView(metric("Kullanılabilir",money(Math.max(0,c.optDouble("limit")-debt(c)))),new LinearLayout.LayoutParams(0,-2,1));b.addView(r);body.addView(b);LinearLayout actions=new LinearLayout(this);actions.setPadding(0,d(10),0,0);Button e=btn("− Gider",RED);e.setOnClickListener(v->addTx(idx,"expense"));Button in=btn("+ Gelir / Ödeme",GREEN);in.setOnClickListener(v->addTx(idx,"income"));actions.addView(e,new LinearLayout.LayoutParams(0,d(48),1));actions.addView(in,new LinearLayout.LayoutParams(0,d(48),1));body.addView(actions);title("İşlemler");JSONArray a=c.optJSONArray("tx");if(a==null||a.length()==0)note("Bu kartta henüz işlem yok.");else for(int j=a.length()-1;j>=0;j--)txRow(idx,a.optJSONObject(j));Button del=btn("Kartı sil",RED);del.setOnClickListener(v->new AlertDialog.Builder(this).setTitle("Kart silinsin mi?").setMessage("Tüm işlem kayıtları da silinir.").setPositiveButton("Sil",(x,w)->{JSONArray n=new JSONArray();for(int k=0;k<cards.length();k++)if(k!=idx)n.put(cards.opt(k));cards=n;save();listCards();}).setNegativeButton("Vazgeç",null).show());LinearLayout.LayoutParams l=new LinearLayout.LayoutParams(-1,d(46));l.setMargins(0,d(22),0,0);body.addView(del,l);}
 void transactions(){screen("Tüm işlemler",2);Button add=btn("+ İşlem ekle",BLUE);add.setOnClickListener(v->chooseCard());body.addView(add,new LinearLayout.LayoutParams(-1,d(48)));title("Geçmiş");boolean any=false;for(int i=0;i<cards.length();i++){JSONObject c=cards.optJSONObject(i);JSONArray a=c==null?null:c.optJSONArray("tx");if(a!=null)for(int j=a.length()-1;j>=0;j--){txRow(i,a.optJSONObject(j));any=true;}}if(!any)note("Henüz işlem kaydı yok.");}
 void txRow(int ci,JSONObject z){if(z==null)return;JSONObject c=cards.optJSONObject(ci);boolean e=z.optString("type").equals("expense");LinearLayout b=box();LinearLayout r=new LinearLayout(this);LinearLayout info=new LinearLayout(this);info.setOrientation(LinearLayout.VERTICAL);String n=z.optString("note");if(n.isEmpty())n=e?"Harcama":"Ödeme / iade";info.addView(t(n,14,TEXT,true));info.addView(t(c.optString("bank")+" • "+new SimpleDateFormat("dd MMM yyyy HH:mm",TR).format(new Date(z.optLong("date"))),11,MUTED,false));r.addView(info,new LinearLayout.LayoutParams(0,-2,1));r.addView(t((e?"− ":"+ ")+money(z.optDouble("amount")),15,e?RED:GREEN,true));b.addView(r);LinearLayout.LayoutParams l=new LinearLayout.LayoutParams(-1,-2);l.setMargins(0,d(8),0,0);body.addView(b,l);}
 boolean recent(int max){int n=0;for(int i=cards.length()-1;i>=0&&n<max;i--){JSONObject c=cards.optJSONObject(i);JSONArray a=c==null?null:c.optJSONArray("tx");if(a!=null)for(int j=a.length()-1;j>=0&&n<max;j--){txRow(i,a.optJSONObject(j));n++;}}return n>0;}
 EditText input(String hint,boolean num){EditText e=new EditText(this);e.setHint(hint);e.setSingleLine();if(num)e.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);return e;} double val(EditText e){try{return Double.parseDouble(e.getText().toString().trim().replace(',','.'));}catch(Exception x){return -1;}}
 void addCard(){LinearLayout f=new LinearLayout(this);f.setOrientation(LinearLayout.VERTICAL);f.setPadding(d(22),0,d(22),0);Spinner bank=new Spinner(this);bank.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,BANKS));EditText name=input("Kart adı (ör. World)",false),lim=input("Kart limiti",true),de=input("Şu anki borç",true);f.addView(bank);f.addView(name);f.addView(lim);f.addView(de);AlertDialog q=new AlertDialog.Builder(this).setTitle("Yeni kart ekle").setView(f).setPositiveButton("Ekle",null).setNegativeButton("Vazgeç",null).create();q.setOnShowListener(x->q.getButton(-1).setOnClickListener(v->{double l=val(lim),dd=de.getText().toString().trim().isEmpty()?0:val(de);if(l<=0){lim.setError("Limit girin");return;}try{JSONObject c=new JSONObject();c.put("bank",BANKS[bank.getSelectedItemPosition()]);c.put("name",name.getText().toString().trim().isEmpty()?"Kredi Kartı":name.getText().toString().trim());c.put("limit",l);c.put("debt",Math.max(0,dd));c.put("tx",new JSONArray());cards.put(c);save();q.dismiss();listCards();}catch(Exception z){}}));q.show();}
 void chooseCard(){if(cards.length()==0){Toast.makeText(this,"Önce kart ekleyin",0).show();addCard();return;}String[] a=new String[cards.length()];for(int i=0;i<a.length;i++){JSONObject c=cards.optJSONObject(i);a[i]=c.optString("bank")+" — "+c.optString("name");}new AlertDialog.Builder(this).setTitle("Kart seç").setItems(a,(x,w)->addTx(w,null)).show();}
 void addTx(int idx,String fixed){JSONObject c=cards.optJSONObject(idx);LinearLayout f=new LinearLayout(this);f.setOrientation(LinearLayout.VERTICAL);f.setPadding(d(22),0,d(22),0);Spinner type=new Spinner(this);type.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"Gider / Harcama","Gelir / Ödeme-İade"}));if("income".equals(fixed))type.setSelection(1);if(fixed!=null)type.setEnabled(false);EditText am=input("Tutar",true),no=input("Açıklama (Market, ödeme...)",false);f.addView(type);f.addView(am);f.addView(no);AlertDialog q=new AlertDialog.Builder(this).setTitle("İşlem ekle").setView(f).setPositiveButton("Kaydet",null).setNegativeButton("Vazgeç",null).create();q.setOnShowListener(x->q.getButton(-1).setOnClickListener(v->{double a=val(am);if(a<=0){am.setError("Tutar girin");return;}try{JSONObject z=new JSONObject();z.put("type",fixed!=null?fixed:(type.getSelectedItemPosition()==0?"expense":"income"));z.put("amount",a);z.put("note",no.getText().toString().trim());z.put("date",System.currentTimeMillis());c.optJSONArray("tx").put(z);cards.put(idx,c);save();q.dismiss();detail(idx);}catch(Exception e){}}));q.show();}
 @Override public void onBackPressed(){summary();}
}
